### ISSUE TITLE
Adding a class will override ALL utilities layer

### ISSUE THREAD

**Issue by imsus** [windicss/vite-plugin-windicss#149] opened 2021-04-23 03:18 UTC
**Describe the bug**
I'm just adding 1 class into vue template. But the output override all utilites layer.

https://user-images.githubusercontent.com/1058471/115812806-35961580-a41c-11eb-8f56-e9d6e87d0923.mp4

**Minimal Reproductions**
1. Run `vite` on project root
2. Try to add 1 class
3. All other class gone inside utilities layer

### `vite.config.ts`
![image](https://user-images.githubusercontent.com/1058471/115812980-945b8f00-a41c-11eb-9c85-a494d85286b2.png)

### `windi.config.ts`
![image](https://user-images.githubusercontent.com/1058471/115813027-a2111480-a41c-11eb-870e-4a98f8890394.png)

### `main.ts`
![image](https://user-images.githubusercontent.com/1058471/115813077-b8b76b80-a41c-11eb-8471-debfc03fe988.png)

**Versions**
- vite-plugin-windicss: `^0.15.6`
- vite: `^2.2.1`
- vue: `3.0.11`

**Additonal Context**
I try to split the `virtual:windi.css` into `virtual:windi-base.css`, `virtual:windi-components.css`, `virtual:windi-utilities.css` also doesn't work.

**Comment by antfu** [comment] 2021-04-23 03:35
Sorry for the regression, should be fixed in 0.15.7. Thanks.

**Closed** 2021-04-23 03:34 UTC
Labels: bug

**Comment by kongmoumou** [comment] 2021-04-23 06:02
Thanks~, I just met the same bug and the fix works for me. 🎉
